import { PRODUCT_ROWS } from './constants.js';
import { createEmptyAppendix } from './contractNumberFormat.js';
import { defaultProductDetailFields } from './productDetailTypes.js';
import { createEmptyLeader } from './projectLeaders.js';
import { createEmptyMember } from './projectMembers.js';
import type { DataEntryFormData } from './types.js';

const emptyProducts = PRODUCT_ROWS.map((row) => ({
  id: row.id,
  label: row.label,
  committed: '0',
  actual: '0',
}));

export const defaultFormData: DataEntryFormData = {
  contractNumber: '',
  contractSeq: '',
  contractYear: '',
  contractSignedAt: '',
  contractAppendix: '',
  contractAppendixSeq: '',
  contractAppendixYear: '',
  contractAppendixSignedAt: '',
  contractAppendices: [createEmptyAppendix()],
  projectCode: '',
  gcnNumber: '',
  gcnIssuedAt: '',
  gcnPlace: '',
  title: '',
  principalInvestigator: '',
  birthYear: '',
  leaders: [createEmptyLeader()],
  members: [createEmptyMember()],
  researchFields: [],
  researchType: '',
  categoryTags: [],
  categoryOther: '',
  department: '',
  facultyUnits: [],
  decisionReview: '',
  decisionApprove: '',
  decisionAppraisal: '',
  decisionAcceptance: '',
  totalBudget: '0',
  contractedBudget: '0',
  nonContractedBudget: '0',
  otherFunding: '0',
  settledBudget: '0',
  installment1: '0',
  installment2: '0',
  installment3: '0',
  durationText: '',
  startDate: '',
  endDate: '',
  extensionDate: '',
  bcAssessmentDate: '',
  progressReportDates: ['', '', '', ''],
  executionProgress: 'on_time',
  reportSubmissionNote: '',
  meetingNtDate: '',
  outputSummary: '',
  projectStatus: 'in_progress',
  yearNt: '',
  academicYear: '',
  products: emptyProducts,
  productActualDetail: '',
  ...defaultProductDetailFields(),
  reminderAt: '',
  completionAt: '',
  principalGender: 'male',
  principalEmail: '',
  supervisorId: '',
  reviewBatch: '',
  sequenceNumber: '',
  sequenceYear: '',
  transferForward: false,
  liquidationReason: '',
  generalNotes: '',
};
