import { PRODUCT_ROWS } from './constants.js';
import type { DataEntryFormData } from './types.js';

const emptyProducts = PRODUCT_ROWS.map((row) => ({
  id: row.id,
  label: row.label,
  committed: '0',
  actual: '0',
}));

export const defaultFormData: DataEntryFormData = {
  contractNumber: '',
  contractAppendix: '',
  projectCode: '',
  gcnNumber: '',
  gcnIssuedAt: '',
  gcnPlace: '',
  title: '',
  principalInvestigator: '',
  birthYear: '',
  members: '',
  researchFields: [],
  researchType: '',
  categoryTags: [],
  categoryOther: '',
  department: '',
  facultyUnits: [],
  decisionReview: '',
  decisionApprove: '',
  totalBudget: '0',
  contractedBudget: '0',
  nonContractedBudget: '0',
  otherFunding: '0',
  installment1: '0',
  installment2: '0',
  installment3: '0',
  durationText: '',
  startDate: '',
  endDate: '',
  extensionDate: '',
  bcAssessmentDate: '',
  progressReportDates: ['', '', '', ''],
  executionProgress: 'on_time',
  reportSubmissionNote: '',
  meetingNtDate: '',
  outputSummary: '',
  projectStatus: 'in_progress',
  yearNt: '',
  academicYear: '',
  products: emptyProducts,
  productActualDetail: '',
  reminderAt: '',
  completionAt: '',
  principalGender: 'male',
  principalEmail: '',
  supervisorId: '',
  transferForward: false,
  liquidationReason: '',
  generalNotes: '',
};
