/** Bộ môn lists keyed by Đơn vị công tác (`FACULTY_UNIT_OPTIONS` names). */
export const DEPARTMENTS_BY_WORK_UNIT: Record<string, readonly string[]> = {
  'Trường Y': [
    'Chẩn đoán hình ảnh',
    'Chấn thương chỉnh hình – PHCN',
    'Da liễu',
    'Gây mê hồi sức',
    'Giải phẫu học',
    'Hoá sinh',
    'Hồi sức cấp cứu chống độc',
    'Huyết học',
    'Lao khoa',
    'Lao và Bệnh phổi',
    'Mắt',
    'Mô phôi – Giải phẫu bệnh',
    'Ngoại thần kinh',
    'Ngoại tổng quát',
    'Nhi',
    'Nhiễm',
    'Nội thần kinh',
    'Nội tiết',
    'Nội tổng quát',
    'Phẫu thuật lồng ngực và Tim mạch',
    'Phụ sản',
    'Tai Mũi Họng',
    'Tâm thần',
    'Tạo hình – Thẩm mỹ',
    'Tiết niệu học',
    'Ung bướu',
    'Vi sinh – Ký sinh',
    'Y đức – Xã hội học – Chăm sóc giảm nhẹ',
    'Sinh lý – Sinh lý bệnh – Miễn dịch – Dược lý',
  ],
  'Trường Dược': [
    'Bào chế',
    'Công nghệ Dược phẩm',
    'Công nghệ thông tin Dược',
    'Dược lâm sàng',
    'Dược liệu – Dược học cổ truyền',
    'Dược Lý',
    'Hóa Dược',
    'Hóa hữu cơ',
    'Hóa sinh',
    'Phân tích – Kiểm nghiệm',
    'Quản lý Dược',
    'Vi sinh – Ký sinh',
  ],
  'Trường Điều dưỡng – Kỹ thuật Y học': [
    'Bệnh học lâm sàng',
    'Điều dưỡng',
    'Gây mê hồi sức',
    'Giải phẫu – Sinh lý',
    'Hộ sinh',
    'Kỹ thuật hình ảnh',
    'Phục hồi chức năng',
    'Xét nghiệm',
  ],
  'Khoa Răng Hàm Mặt': [
    'Bệnh học miệng',
    'Cấy ghép nha khoa',
    'Chẩn đoán hình ảnh RHM',
    'Chỉnh hình răng mặt',
    'Chữa răng – Nội nha',
    'Kỹ thuật phục hình răng',
    'Nha chu',
    'Nha khoa cơ sở',
    'Nha khoa cộng đồng',
    'Nha khoa Tổng quát',
    'Nha khoa trẻ em',
    'Phẫu thuật hàm mặt',
    'Phẫu thuật miệng',
    'Phục hình răng',
  ],
  'Khoa Y học cổ truyền': [
    'Bào chế Đông dược',
    'Châm cứu',
    'Dược học cổ truyền',
    'Dưỡng sinh',
    'Nhi khoa Đông y',
    'Nội khoa Đông y',
    'Y học cổ truyền cơ sở',
  ],
  'Khoa Y tế công cộng': [
    'Dân số học – Sức khỏe môi trường',
    'Dịch tễ học',
    'Dinh dưỡng và thực phẩm',
    'Giáo dục sức khỏe & Tâm lý y học',
    'Quản lý y tế',
    'Sức khỏe cộng đồng',
    'Thống kê & Tin học Y học',
  ],
  'Khoa Khoa học cơ bản': [
    'Toán học',
    'Vật lý',
    'Hóa học',
    'Sinh học',
    'Ngoại ngữ',
    'Khoa học Xã hội và Nhân văn',
    'Giáo dục thể chất',
    'Giáo dục quốc phòng',
    'Tin học',
  ],
};

export function departmentsForWorkUnit(workUnit: string): readonly string[] {
  return DEPARTMENTS_BY_WORK_UNIT[workUnit.trim()] ?? [];
}

export function isDepartmentInWorkUnit(workUnit: string, department: string): boolean {
  const dept = department.trim();
  if (!dept) return true;
  return departmentsForWorkUnit(workUnit).includes(dept);
}
